"""add task target date

Revision ID: de5d40004c9d
Revises: 23c4905f352b
Create Date: 2026-06-13 00:41:44.830642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'de5d40004c9d'
down_revision: Union[str, None] = '23c4905f352b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
